# fly.toml app configuration file generated for truledgr-dashboard on 2025-06-20T19:29:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'truledgr-dashboard'
primary_region = 'ord'

[env]
  VITE_API_URL = "https://api.truledgr.com" # Set this to your deployed API URL


[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
