repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
  # ruff pre-commit hook removed temporarily due to environment checkout issues
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: v0.26.0
  #   hooks:
  #     - id: ruff
  #       args: ["check"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
  - repo: local
    hooks:
      - id: js-lint
        name: JS Lint (npm)
        entry: bash -c "cd dashboard && npm install --no-audit --no-fund && npm run lint && cd ../landing && npm install --no-audit --no-fund && npm run lint"
        language: system
        pass_filenames: false
