app = "truledgr-traefik"
primary_region = "ord"

[env]
  EMAIL = "admin@mcguire.technology"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[[mounts]]
  source = "traefik_certificates"
  destination = "/certificates"

[build]
  dockerfile = "traefik.Dockerfile"
