site_name: TruLedgr Documentation
site_description: Comprehensive documentation for the TruLedgr personal finance application
site_author: McGuire Technology
site_url: https://docs.truledgr.app

# Repository
repo_name: McGuireTechnology/TruLedgr
repo_url: https://github.com/McGuireTechnology/TruLedgr
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 McGuire Technology

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/chart-line
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McGuireTechnology/TruLedgr
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/mcguiretechnology
  version:
    provider: mike

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: mcguiretechnology
      repo: truledgr
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Managing Finances: user/managing-finances.md
    - FAQ: user/faq.md
  - Tutorials:
    - Quick Start Guide: tutorials/quick-start.md
    - Your First Budget: tutorials/first-budget.md
    - Family Finance Setup: tutorials/family-setup.md
    - Importing Your Data: tutorials/importing-data.md
  - Developer Guide:
    - Overview: developer/overview.md
  - Integrations:
    - Overview: integrations/overview.md
  - Security:
    - Overview: security/overview.md
  - Support:
    - Overview: support/overview.md
  - Reference:
    - Glossary: reference/glossary.md
    - Keyboard Shortcuts: reference/keyboard-shortcuts.md
    - File Formats: reference/file-formats.md
    - System Requirements: reference/system-requirements.md
    - Feature Comparison: reference/feature-comparison.md
    - Data Model: reference/data-model.md
  - Contributing:
    - Guidelines: contributing/guidelines.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Additional JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
