site_name: TruLedgr Documentation
site_description: Documentation for TruLedgr platform
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Contributors: contributors.md
  - Support: support.md
  - Release Notes: RELEASE.md
  - Changelog: changelog/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
