site_name: TruLedgr
site_description: Comprehensive personal finance application suite with multi-platform support for monthly cycles, estate planning, and tax planning
site_author: McGuire Technology, LLC
site_url: https://truledgr.app
repo_url: https://github.com/McGuireTechnology/TruLedgr
repo_name: McGuireTechnology/TruLedgr
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 McGuire Technology, LLC

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    # Navigation
    - navigation.instant          # Instant loading (SPA-like)
    - navigation.instant.prefetch # Prefetch pages for faster navigation
    - navigation.instant.progress # Show progress indicator
    - navigation.tracking         # Update URL with active anchor
    - navigation.tabs             # Top-level sections as tabs
    - navigation.tabs.sticky      # Sticky tabs
    - navigation.sections         # Render sections in navigation
    - navigation.expand           # Expand sections by default
    - navigation.path             # Show breadcrumb path
    - navigation.indexes          # Section index pages
    - navigation.top              # Back to top button
    - navigation.footer           # Footer with prev/next links
    
    # Table of contents
    - toc.follow                  # TOC follows scroll
    - toc.integrate               # TOC in navigation
    
    # Search
    - search.suggest              # Search suggestions
    - search.highlight            # Highlight search terms
    - search.share                # Share search results
    
    # Content
    - content.code.copy           # Copy button for code blocks
    - content.code.annotate       # Code annotations
    - content.tabs.link           # Link content tabs
    - content.tooltips            # Improved tooltips
    
    # Header
    - header.autohide             # Hide header on scroll

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_file: tags.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McGuireTechnology/TruLedgr
      name: TruLedgr on GitHub
    - icon: fontawesome/solid/globe
      link: https://truledgr.app
      name: TruLedgr Website
  
  generator: false  # Remove "Made with Material for MkDocs"
  
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Quick Start: getting-started/quick-start.md
      - Running the Applications: getting-started/running-apps.md
      - Development Setup: getting-started/dev-setup.md
  - Architecture:
      - architecture/index.md
      - Overview: architecture/overview.md
      - API Backend: architecture/api.md
      - Frontend Web: architecture/frontend.md
      - Mobile Apps: architecture/mobile.md
      - Database Design: architecture/database.md
      - Authentication: architecture/auth.md
  - API Reference:
      - api/index.md
      - Endpoints: api/endpoints.md
      - Models: api/models.md
      - Authentication: api/authentication.md
  - Deployment:
      - deployment/index.md
      - DigitalOcean: deployment/digitalocean.md
      - Environment Variables: deployment/environment.md
      - CI/CD: deployment/cicd.md
  - Contributing:
      - contributing/index.md
      - Development Workflow: contributing/workflow.md
      - Code Style: contributing/style.md
      - Testing: contributing/testing.md
  - Tags: tags.md
