http:
  routers:
    dashboard:
      rule: "Host(`dashboard.truledgr.app`)"
      service: dashboard-service
      entryPoints:
        - https
      tls:
        certResolver: le
    api:
      rule: "Host(`api.truledgr.app`)"
      service: api-service
      entryPoints:
        - https
      tls:
        certResolver: le
  services:
    dashboard-service:
      loadBalancer:
        servers:
          - url: "http://truledgr-dashboard.internal:80"
    api-service:
      loadBalancer:
        servers:
          - url: "http://truledgr-backend.internal:8080"
