alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: api.truledgr.app
  type: PRIMARY
  zone: api.truledgr.app
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: truledgr
    match:
      path:
        prefix: /
name: truledgr-api
region: nyc
# PRE_DEPLOY job runs database migrations before app instances start
jobs:
- name: db-migrate
  kind: PRE_DEPLOY
  environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_TIME
    value: ${SECRET_KEY}
  github:
    branch: staging
    deploy_on_push: false
    repo: McGuireTechnology/TruLedgr
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  run_command: |
    set -e
    echo "🚀 Starting database migration..."
    echo "📦 Installing Poetry..."
    python3 -m pip install --upgrade pip
    python3 -m pip install poetry
    echo "✅ Poetry installed"
    echo "📦 Installing project dependencies..."
    python3 -m poetry install --no-dev --no-interaction --no-root
    echo "✅ Dependencies installed"
    echo "🔄 Running migrations..."
    cd api
    python3 -m poetry run alembic upgrade head
    echo "✅ Database migrations completed successfully"
  source_dir: /
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SECRET_KEY}
  - key: VITE_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.truledgr.app
  github:
    branch: staging
    deploy_on_push: true
    repo: McGuireTechnology/TruLedgr
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: truledgr
  source_dir: /
