name: truledgr-api
region: nyc1

# Environment variables
envs:
  - key: ENVIRONMENT
    value: production
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SENTRY_DSN
    scope: RUN_AND_BUILD_TIME
    type: SECRET

# Services
services:
  - name: api
    source_dir: /
    
    # Build configuration
    build:
      method: docker
      dockerfile_path: Dockerfile
    
    # Runtime environment
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 8000

    # Health checks
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Routes
    routes:
      - path: /

# Domains (optional - configure after deployment)
# domains:
#   - domain: api.truledgr.app
#     type: PRIMARY
