entryPoints:
  http:
    address: "0.0.0.0:8080"
  https:
    address: "0.0.0.0:8443"

api:
  dashboard: true
  insecure: false

providers:
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
  le:
    acme:
      email: ${EMAIL}
      storage: /certificates/acme.json
      tlsChallenge: true

log:
  level: INFO

accessLog: {}

http:
  routers:
    traefik-dashboard:
      rule: "Host(`proxy.truledgr.app`) || Host(`truledgr-proxy.fly.dev`) || Host(`proxy.staging.truledgr.app`) || Host(`proxy`) || Host(`proxy.staging`)"
      service: api@internal
      entryPoints:
        - https
      tls:
        certResolver: le
    dashboard:
      rule: "Host(`dashboard.truledgr.app`) || Host(`dashboard.staging.truledgr.app`) || Host(`dashboard`) || Host(`dashboard.staging`)"
      service: dashboard-service
      entryPoints:
        - https
      tls:
        certResolver: le
    api:
      rule: "Host(`api.truledgr.app`) || Host(`api.staging.truledgr.app`) || Host(`api`) || Host(`api.staging`)"
      service: api-service
      entryPoints:
        - https
      tls:
        certResolver: le
    adminer:
      rule: "Host(`adminer.truledgr.app`) || Host(`adminer.staging.truledgr.app`) || Host(`adminer`) || Host(`adminer.staging`)"
      service: adminer-service
      entryPoints:
        - https
      tls:
        certResolver: le
  services:
    dashboard-service:
      loadBalancer:
        servers:
          - url: "http://truledgr-dashboard.internal:80"
    api-service:
      loadBalancer:
        servers:
          - url: "http://truledgr-api.internal:8080"
    adminer-service:
      loadBalancer:
        servers:
          - url: "http://truledgr-adminer.internal:8080"
