name: Suggest changelog entry

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  suggest-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch commits
        run: git fetch --prune --unshallow || true

      - name: Generate changelog suggestion
        id: changelog
        run: |
          # This is a simple heuristic using commit messages on the PR to form a changelog.
          # For more advanced generation, replace this with a bot or use Conventional Commit parser.
          COMMITS=$(git log --format=%s "origin/${{ github.event.pull_request.base.ref }}..HEAD")
          echo "Commits: $COMMITS"
          SUGGEST=""
          while read -r line; do
            if [[ $line =~ ^feat ]]; then
              SUGGEST+="- ${line}\n"
            elif [[ $line =~ ^fix ]]; then
              SUGGEST+="- ${line}\n"
            fi
          done <<< "$COMMITS"
          if [[ -z "$SUGGEST" ]]; then
            SUGGEST="- No changelog-worthy commits detected; please add a short note."
          fi
          echo "suggestion<<EOF" >> $GITHUB_OUTPUT
          $SUGGEST
          EOF

      - name: Post suggestion as PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const pr = context.payload.pull_request
            const body = `Suggested changelog entries (automated):\n\n${{ steps.changelog.outputs.suggestion }}`
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            })
