name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write  # Required for peaceiris/actions-gh-pages to push to gh-pages branch

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (Poetry)
        run: |
          poetry install --no-interaction --no-ansi

      - name: Build documentation
        run: |
          poetry run mkdocs build --site-dir site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: truledgr.app

      - name: Validate build (staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "✅ MkDocs build successful on staging branch"
          echo "📦 Site built to ./site directory"
          echo "🚀 Will deploy to GitHub Pages when merged to main"
          ls -lah ./site