name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches: [ main, staging ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (Poetry)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Build MkDocs site
        run: |
          poetry run mkdocs build --site-dir site

      - name: Add CNAME for apex domain
        run: |
          echo "truledgr.app" > site/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1